/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.model.Relatorio;
import com.mycompany.DAO.RelatorioDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luka
 */
public class RelatorioSintetico extends javax.swing.JFrame {

    /**
     * Creates new form Relatório
     */
    public int idVenda = 0;
    public int numeroLinha = 0;

    Relatorio objRelatorio;

    public RelatorioSintetico() {
        initComponents();

        setLocationRelativeTo(null);
        objRelatorio = new Relatorio();

        //Carregar todos os clientes na tabela ao iniciar este JFrame
        CarregarJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorioSintetico = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDataInicial = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataFinal = new com.toedter.calendar.JDateChooser();
        btnDetalhes = new javax.swing.JButton();
        btnDia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotalVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório sintético", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 0, 18))); // NOI18N

        tblRelatorioSintetico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código da Venda", "Código do Cliente", "Nome do Cliente", "Data de compra", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(tblRelatorioSintetico);

        btnVoltar.setText("<< VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel5.setText("Gere um relatório a partir de um intervalo de tempo:");

        txtDataInicial.setDateFormatString("dd/MM/yyyy");

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        txtDataFinal.setDateFormatString("dd/MM/yyyy");

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        btnDia.setText("Gerar dia");
        btnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Valor total das vendas no intervalo: ");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jLabel4.setText("R$");

        txtValorTotalVendas.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        txtValorTotalVendas.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotalVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGerar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDia, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnDia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGerar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtValorTotalVendas))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        Date dataInicial = new java.sql.Date(txtDataInicial.getDate().getTime());
        Date dataFinal = new java.sql.Date(txtDataFinal.getDate().getTime());

        ArrayList<Relatorio> listaVendasRealizadas = RelatorioDAO.consultarIntervaloVendas(dataInicial, dataFinal);

        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("Código da venda");
        tmVendas.addColumn("Código do cliente");
        tmVendas.addColumn("Nome do cliente");
        tmVendas.addColumn("Data da compra");
        tmVendas.addColumn("Valor total");

        //Defina sua estrutura com a estrutura tmClientes;
        tblRelatorioSintetico.setModel(tmVendas);

        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmVendas.setRowCount(0);
        double valorTotalVendas = 0;
        for (Relatorio c : listaVendasRealizadas) {
            tmVendas.addRow(new Object[]{c.getId(), c.getIdCliente(), c.getNomeCliente(), c.getDataVenda(), c.getValorTotal()});
            valorTotalVendas += c.getValorTotal();
        }
        valorTotalVendas = Math.round(valorTotalVendas * 100.0) / 100.0;
        txtValorTotalVendas.setText(String.valueOf(valorTotalVendas));

    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        numeroLinha = tblRelatorioSintetico.getSelectedRow();
        idVenda = Integer.parseInt(tblRelatorioSintetico.getModel().getValueAt(numeroLinha, 0).toString());
        System.out.println(idVenda);
        objRelatorio.setId(idVenda);
        RelatorioAnalitico telaRelatorioAnalitico = new RelatorioAnalitico(objRelatorio);
        telaRelatorioAnalitico.setVisible(true);
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void btnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaActionPerformed
        String dataInicial = String.valueOf(new java.sql.Date(txtDataInicial.getDate().getTime())).replaceAll("-", "/");
        Date data = new java.sql.Date(txtDataInicial.getDate().getTime());

        System.out.println("dataInicial: " + dataInicial);

        ArrayList<Relatorio> listaVendasRealizadas = RelatorioDAO.consultarDiaVenda(data);

        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("Código da venda");
        tmVendas.addColumn("Código do cliente");
        tmVendas.addColumn("Nome do cliente");
        tmVendas.addColumn("Data da compra");
        tmVendas.addColumn("Valor total");

        //Defina sua estrutura com a estrutura tmClientes;
        tblRelatorioSintetico.setModel(tmVendas);

        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmVendas.setRowCount(0);

        double valorTotalVendas = 0;

        for (Relatorio c : listaVendasRealizadas) {
            tmVendas.addRow(new Object[]{c.getId(), c.getIdCliente(), c.getNomeCliente(), c.getDataVenda(), c.getValorTotal()});
            valorTotalVendas += c.getValorTotal();
        }
        valorTotalVendas = Math.round(valorTotalVendas * 100.0) / 100.0;
        txtValorTotalVendas.setText(String.valueOf(valorTotalVendas));
    }//GEN-LAST:event_btnDiaActionPerformed

    public void CarregarJTable() {

        ArrayList<Relatorio> listaVendasRealizadas = RelatorioDAO.consultarVendas();

        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("Código da venda");
        tmVendas.addColumn("Código do cliente");
        tmVendas.addColumn("Nome do cliente");
        tmVendas.addColumn("Data da compra");
        tmVendas.addColumn("Valor total");

        //Defina sua estrutura com a estrutura tmClientes;
        tblRelatorioSintetico.setModel(tmVendas);

        //Limpo a tabela, excluindo todas as linhas para depois mostrar os dados novamente
        tmVendas.setRowCount(0);
        double valorTotalVendas = 0;
        for (Relatorio c : listaVendasRealizadas) {
            tmVendas.addRow(new Object[]{c.getId(), c.getIdCliente(), c.getNomeCliente(), c.getDataVenda(), c.getValorTotal()});
            valorTotalVendas += c.getValorTotal();
        }
        valorTotalVendas = Math.round(valorTotalVendas * 100.0) / 100.0;
        txtValorTotalVendas.setText(String.valueOf(valorTotalVendas));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }

        new RelatorioSintetico(); //Create and show the GUI.

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioSintetico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnDia;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRelatorioSintetico;
    private com.toedter.calendar.JDateChooser txtDataFinal;
    private com.toedter.calendar.JDateChooser txtDataInicial;
    private javax.swing.JLabel txtValorTotalVendas;
    // End of variables declaration//GEN-END:variables
}
